### ISSUE TITLE
OpenAPI enum-definitions are not supported in Proto-File generation

### ISSUE THREAD

**Issue by markusbartel1** [googleapis/gnostic-grpc#19]
Why are enums not generated in Proto-File?

**Comment by LorenzHW** [comment]
The way this plugin works is that it gets some data from its parent [gnostic](https://github.com/googleapis/gnostic): 

1. gnostics takes the OpenAPI description, extracts information, and puts it into a ["surface model"](https://github.com/googleapis/gnostic/blob/master/surface/surface.proto).
2. The information contained in the surface model is then used by various plugins (such as gnostic-grpc) to generate some output.

> Why are enums not generated in Proto-File?

Currently, the surface model does not provide any information about enums, therefore this plugin does not get the necessary information about enums.

This would be a two step process to fix this:
1. Fill the surface model with additional information about enums. Filling the surface model with information from the parsed OpenAPI description happens [here](https://github.com/googleapis/gnostic/blob/master/surface/model_openapiv3.go).
2. Update this plugin in order to generate enums as well.

**Comment by markusbartel1** [comment]
Thank you for the explaination. I understand why enums are not supported. I will try to fix this for my purpose.Thank you for the quick answer and your very useful work.
-------- Ursprüngliche Nachricht --------Von: Lorenz Hofmann-Wellenhof <notifications@github.com> Datum: 01.04.20  12:34  (GMT+01:00) An: googleapis/gnostic-grpc <gnostic-grpc@noreply.github.com> Cc: markusbartel1 <markus.bartel@t-online.de>, Author <author@noreply.github.com> Betreff: Re: [googleapis/gnostic-grpc] OpenAPI enum-definitions are not
  supported in Proto-File generation (#19) 
The way this plugin works is that it gets some data from its parent gnostic:

gnostics takes the OpenAPI description, extracts information, and puts it into a "surface model".
The information contained in the surface model is then used by various plugins (such as gnostic-grpc) to generate some output.


Why are enums not generated in Proto-File?

Currently, the surface model does not provide any information about enums, therefore this plugin does not get the necessary information about enums.
This would be a two step process to fix this:

Fill the surface model with additional information about enums. Filling the surface model with information from the parsed OpenAPI description happens here.
Update this plugin in order to generate enums as well.


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/googleapis/gnostic-grpc/issues/19#issuecomment-607170817",
"url": "https://github.com/googleapis/gnostic-grpc/issues/19#issuecomment-607170817",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rverma-jm** [comment]
Facing same issue, 

The generator fails to translate enum in schem to enum in proto.

e.g.
```
"TransactionStatusResponse": {
        "type": "object",
        "properties": {
          "transactionStatus": {
            "type": "string",
            "enum": [
              "SUCCESS",
              "FAILURE",
              "PROCESSING",
              "INITIATED"
            ]
          },
          "transactionDate": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
```
generates
```
message TransactionStatusResponse {
  string transaction_status = 1;

  string transaction_date = 2;
}
```
and omits enum completely.
